In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_hdf('./data/m12i_cluster_data.h5', key='star')

In [4]:
df.head()

,Unnamed: 0,feH,id_stars,radial_distance_stars,redshift_stars,snap_list_stars,star_mass,subhalo_mass_stars,subhalo_peak_mass,subhalo_stellar_mass_stars,vphistar,vrstar,vthetastar,vxstar,vystar,vzstar,xstar,ystar,zstar,cluster_id
73008,73008,-3.873608,4327099,9.211095,2.586207,138,4980.819555,7212108.0,22792022.0,57637.503906,239.335739,-230.501434,181.553940,-112.675156,-343.308136,113.217339,-1.771496,4.111042,-8.050180,1
73089,73089,-2.688378,12736793,15.952224,2.586207,138,4835.979771,7212108.0,22792022.0,57637.503906,71.621208,-256.820892,161.885895,-283.049805,-87.615784,-97.467377,13.269795,8.032511,-3.723538,1
155921,155921,-2.053396,4764646,14.881052,1.100000,262,5222.007720,15022792.0,23190884.0,61523.742188,62.657837,-248.070709,54.305466,24.864803,-178.009537,-190.022400,-5.710719,10.582099,8.766560,2
155922,155922,-2.973717,9335794,12.130770,1.100000,262,5066.419914,15022792.0,23190884.0,61523.742188,-108.005646,-191.695251,-215.668335,-128.202011,-15.208354,279.746429,6.917473,-8.249007,-5.590888,2
155924,155924,-3.693150,10771403,15.310860,1.100000,262,4728.352183,15022792.0,23190884.0,61523.742188,-62.806545,142.767578,157.148590,-49.536232,197.822800,-86.227676,-7.423605,11.882225,6.174565,2